import type { GuideSection } from "./adapt-cards";

export const COMMON_ADAPT_SECTIONS_EN: GuideSection[] = [
  {
    id: "cafe",
    label: "Cafes & restaurants",
    bgClass: "bg-gray-100",
    textClass: "text-text-secondary",
    cards: [
      {
        id: "kiosk",
        emoji: "☕",
        title: "Order at a cafe kiosk",
        situation: "First time ordering at a kiosk in a large cafe like Starbucks or Twosome Place",
        steps: [
          "Tap the kiosk by the entrance or register to start",
          "Choose For here or Takeout",
          "Pick a drink, then size, hot/iced, and extras",
          "Add to cart → Pay",
          "Tap your card or Kakao Pay / Naver Pay QR",
        ],
        tip: "Remember the receipt number — pickup is called by number on the screen or speaker.",
        verification: "quiz",
        quiz: {
          question: "What do you choose first on a cafe kiosk, before picking a drink?",
          options: ["The drink menu", "For here / Takeout", "Pay", "Add to cart"],
          answerIndex: 1,
        },
      },
      {
        id: "restaurant",
        emoji: "🍜",
        title: "Order by speaking at a restaurant",
        situation: "When there is no table tablet and you order from staff",
        steps: [
          "Sit down, then get a menu or scan a QR code",
          "Decide, then raise a hand or call staff",
          "Say the dish name + juseyo (e.g. kimchi-jjigae hana juseyo)",
          "For more than one: du gae juseyo, se gae juseyo",
          "To pay, say gyesan-hae juseyo or hold up your card",
        ],
        phrases: [
          { native: "여기요!", meaning: "Call staff" },
          { native: "이거 주세요", meaning: "Order while pointing" },
          { native: "계산해 주세요", meaning: "Ask for the bill" },
          { native: "포장해 주세요", meaning: "Ask for takeout" },
        ],
        verification: "quiz",
        quiz: {
          question: "What do you say to call a server in a Korean restaurant?",
          options: ["Jeogiyo!", "Yeogiyo!", "Annyeonghaseyo!", "Gamsahamnida!"],
          answerIndex: 1,
        },
      },
    ],
  },
  {
    id: "delivery",
    label: "Delivery apps",
    bgClass: "bg-gray-100",
    textClass: "text-text-secondary",
    cards: [
      {
        id: "baemin",
        emoji: "🛵",
        title: "First order on Baemin",
        situation: "Using a Korean food-delivery app for the first time",
        steps: [
          "Install Baedal Minjok (Baemin) from the App Store or Play Store",
          "Sign up (phone verification) and save a delivery address",
          "Pick a category or search a dish",
          "Choose a store → add items → Place order",
          "Pay with a card or Kakao Pay",
          "Track the rider under Order status",
        ],
        verification: "quiz",
        quiz: {
          question: "Which Baemin tab is for faster single-order delivery?",
          options: ["Regular delivery", "Baemin1", "Store pickup", "Convenience store"],
          answerIndex: 1,
        },
        tip: "Baemin1 is one order, faster, higher fee. Regular delivery batches orders and is cheaper.",
      },
    ],
  },
  {
    id: "hospital",
    label: "Clinics & pharmacies",
    bgClass: "bg-gray-100",
    textClass: "text-text-secondary",
    cards: [
      {
        id: "clinic",
        emoji: "🏥",
        title: "First visit to a neighborhood clinic",
        situation: "A cold or upset stomach — walk-in, no appointment",
        steps: [
          "Search internal medicine or family medicine on Naver/Kakao Map",
          "At reception, show your ARC (or passport) and health-insurance card",
          "If asked Is this your first visit?, say Ne, cheoeum-ieyo",
          "Fill in the intake form (often Korean + English)",
          "Get a prescription, then go to a nearby pharmacy",
        ],
        tip: "Most clinics take walk-ins. With National Health Insurance you typically pay 30%.",
        phrases: [
          { native: "여기가 아파요", meaning: "It hurts here (point)" },
          { native: "열이 나요", meaning: "I have a fever" },
          { native: "소화가 안 돼요", meaning: "Indigestion" },
          { native: "며칠째 기침이 나요", meaning: "I've been coughing for days" },
        ],
        verification: "timer",
        timerSec: 20,
      },
      {
        id: "pharmacy",
        emoji: "💊",
        title: "Fill a prescription at a pharmacy",
        situation: "You left the clinic with a prescription",
        steps: [
          "Go to a nearby pharmacy — look for a green cross",
          "Hand over the prescription plus ARC or insurance card",
          "Wait until your number or name is called",
          "Listen to the dosing (e.g. 3 times a day, 30 minutes after meals)",
        ],
        tip: "Prescriptions are valid for 3 days from the issue date.",
        verification: "timer",
        timerSec: 20,
      },
    ],
  },
  {
    id: "admin",
    label: "Visa & admin",
    bgClass: "bg-gray-100",
    textClass: "text-text-secondary",
    cards: [
      {
        id: "alien-card",
        emoji: "🪪",
        title: "Apply for an Alien Registration Card",
        situation: "Required within 90 days of arrival",
        steps: [
          "Book a visit on HiKorea (hikorea.go.kr)",
          "Go to your immigration office with the booking slip",
          "Fill the form on site (free)",
          "Bring: passport, 1 photo, enrollment certificate (students), ₩30,000 fee",
          "Pickup in about 2–3 weeks when you get a text",
        ],
        tip: "Walk-ins can mean a very long wait. Book first.",
        verification: "timer",
        timerSec: 20,
      },
      {
        id: "community-center",
        emoji: "🏛️",
        title: "First visit to a community center",
        situation: "Address change, certificates, or health-insurance questions",
        steps: [
          "Go to the dong office for your address — bring your ARC",
          "Take a queue number at the entrance",
          "When called, say what you need",
          "You can ask: Yeong-eo hal su inneun bun isseoyo? for English help",
        ],
        tip: "Typical services: move-in report, residence confirmation, insurance questions, certificates.",
        verification: "timer",
        timerSec: 20,
      },
    ],
  },
  {
    id: "transport",
    label: "Transit",
    bgClass: "bg-gray-100",
    textClass: "text-text-secondary",
    cards: [
      {
        id: "tmoney",
        emoji: "🚇",
        title: "Get and use a T-money card",
        situation: "First subway or bus ride",
        steps: [
          "Buy a T-money card at CU, GS25, or 7-Eleven — about ₩2,500",
          "Top up at the same store or a station machine (₩10,000+ is comfortable)",
          "Tap when you board — a beep means it worked",
          "Tap again when you get off or you may be charged extra",
        ],
        tip: "Naver Map and Kakao Map both support English and Japanese for transfers and travel time.",
        verification: "quiz",
        quiz: {
          question: "What happens if you skip the tap when getting off a bus or subway?",
          options: ["Nothing", "You get a warning text", "You are charged extra", "The card is blocked"],
          answerIndex: 2,
        },
      },
    ],
  },
  {
    id: "shopping",
    label: "In-store shopping",
    bgClass: "bg-gray-100",
    textClass: "text-text-secondary",
    cards: [
      {
        id: "olive-sale-intro",
        emoji: "🛍️",
        title: "All-Young sale, from the start",
        situation: "Friends ask what you'll buy at Olive Young during the big sale (early Mar/Jun/Sep/Dec)",
        steps: [
          "All-Young is short for Olive Young, a large K-beauty drugstore",
          "Hot sale is about 4 times a year — biggest discounts then",
          "Before you go, pick 1–3 categories (lip, base, skincare)",
          "Check wishlist, coupons, and membership in the Olive Young app",
        ],
        tip: "In Korean stores it is normal to test products and ask staff. Read the cards below before you go.",
        verification: "quiz",
        quiz: {
          question: "When Korean friends say All-Young, they mean…",
          options: ["An online video app", "Olive Young", "An olive-oil brand", "A shopping mall"],
          answerIndex: 1,
        },
      },
      {
        id: "olive-store-culture",
        emoji: "🏪",
        title: "Store culture — calling staff and stock",
        situation: "The shelf is empty and you are not sure if it is sold out, or if you may ask staff",
        steps: [
          "Saying Staff-nim, dowajuseyo is polite — they expect to check stock",
          "Empty shelf ≠ sold out; it may be in the back or another aisle",
          "Look for a sold-out sticker or ask Is this product in stock?",
          "At Olive Young, staff or the app can check other branches",
          "It is normal to ask more than once if you need several items",
        ],
        tip: "Asking staff is often faster than searching the whole store alone.",
        verification: "quiz",
        quiz: {
          question: "The product is not on the shelf. What fits Korean store culture?",
          options: [
            "Assume sold out and leave",
            "Ask staff to check stock and location",
            "Only try another brand's store",
            "Wait quietly",
          ],
          answerIndex: 1,
        },
      },
      {
        id: "olive-store",
        emoji: "💄",
        title: "Find and test products in store",
        situation: "Too many SKUs, and Warm best / Cool best tags are confusing",
        steps: [
          "Warm best / Cool best tags hint at personal color, not a rule",
          "If it is behind the display, ask Can you take this out for me?",
          "If this store is out, ask about another branch",
          "At the tester, ask May I test this? then swatch on the hand or lip",
        ],
        phrases: [
          { native: "이 제품을 꺼내줄 수 있나요?", meaning: "Please take this off the shelf / from the back" },
          { native: "이 제품이 다른 매장에 있나요?", meaning: "Do other stores have it?" },
          { native: "근처 다른 올리브영에 재고 있나요?", meaning: "Stock at a nearby Olive Young?" },
          { native: "직원님, 도와주세요", meaning: "Excuse me, I need help" },
          { native: "테스트 해봐도 되나요?", meaning: "May I test this?" },
        ],
        tip: "Liking pink does not decide warm vs cool. Test on your skin.",
        verification: "quiz",
        quiz: {
          question: "Natural way to ask about stock at another franchise store?",
          options: [
            "How much is this?",
            "Do other stores have this product?",
            "Check out, please",
            "Please wrap this",
          ],
          answerIndex: 1,
        },
      },
      {
        id: "olive-discount",
        emoji: "💳",
        title: "In-store discounts — check before you pay",
        situation: "Sale prices, membership, coupons, and card deals overlap",
        steps: [
          "Order: sale price → Olive Young / CJ ONE membership → app coupons → co-branded card / pay apps",
          "Download coupons in the app before you visit",
          "Card deals change by season — check the app or in-store POP",
          "At the register ask which discounts apply before you pay",
          "Some deals are app-only or online-only",
        ],
        phrases: [
          { native: "회원 할인 되나요?", meaning: "Member discount?" },
          { native: "쿠폰 사용할 수 있나요?", meaning: "Can I use a coupon?" },
          { native: "제휴카드 할인 되나요?", meaning: "Partner-card discount?" },
          { native: "할인 다 적용하면 얼마예요?", meaning: "What's the total after discounts?" },
        ],
        tip: "If a sale feels like no discount, you probably missed membership, coupon, or card rules.",
        verification: "timer",
        timerSec: 25,
      },
      {
        id: "korea-beauty-trend",
        emoji: "🇰🇷",
        title: "What's trending in Korean beauty?",
        situation: "Cool/warm, glossy/matte, and idol makeup looks are hard to track",
        steps: [
          "K-beauty splits by tone, finish, skin type, and personal color",
          "Warm best / Cool best tags are hints, not your favorite color",
          "Glossy vs matte often rotates by season",
          "Idol and YouTuber makeup is the fastest trend signal",
          "Use nüami video-link summaries, then pick 3 candidates before the store",
        ],
        tip: "One look at current makeup videos saves a lot of time in store.",
        verification: "quiz",
        quiz: {
          question: "Fastest way to read current K-beauty trends?",
          options: [
            "Buy the most expensive item",
            "Watch idol / beauty YouTuber makeup",
            "Grab anything in store",
            "Search English reviews only",
          ],
          answerIndex: 1,
        },
      },
      {
        id: "olive-purchase",
        emoji: "📱",
        title: "Online + offline buying",
        situation: "No discount in store, sold out online",
        steps: [
          "Online sold-out often means only stores have stock — check store inventory in the app",
          "Use a nüami action guide as a pre-visit checklist",
          "International students can usually join membership with passport or ARC",
          "Wishlist + restock alerts help until the next sale",
        ],
        tip: "The gap is usually store culture + discount rules + trend info. Read this tab in order before you go.",
        verification: "timer",
        timerSec: 20,
      },
    ],
  },
];
